<Project>
  <PropertyGroup>
    <Version>0.0.0</Version>
    <AssemblyVersion>$(Version).0</AssemblyVersion>
    <FileVersion>$(Version).0</FileVersion>
    <InformationalVersion>$(Version)</InformationalVersion>
    <Authors>John Strand and NetChatx Contributors</Authors>
    <Company>NetChatx</Company>
    <Product>NetChatx</Product>
    <Copyright>Copyright © 2026</Copyright>
    <PackageProjectUrl>https://github.com/johnstrand/netchatx</PackageProjectUrl>
    <RepositoryUrl>https://github.com/johnstrand/netchatx</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
</Project>
