<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NetChatx.Core\NetChatx.Core.csproj" />
    <ProjectReference Include="..\NetChatx.Protocol.Xeps\NetChatx.Protocol.Xeps.csproj" />
    <ProjectReference Include="..\NetChatx.Storage\NetChatx.Storage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Terminal.Gui" Version="2.4.17" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
